"""HTML report generator for AI Coder Debt analysis."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models import AnalysisResult


class HTMLReportGenerator:
    """Generate standalone HTML reports from analysis results."""

    def generate(self, result: "AnalysisResult") -> str:
        """Generate HTML report string.

        Args:
            result: Analysis result to format.

        Returns:
            HTML string.
        """
        # Build HTML document
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Coder Debt Analysis Report</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>AI Coder Debt Analysis Report</h1>
            <div class="meta">
                <p><strong>Project:</strong> <code>{result.project_path}</code></p>
                <p><strong>Timestamp:</strong> {result.timestamp}</p>
            </div>
        </header>

        <section class="summary">
            <h2>Metrics Summary</h2>
            {self._generate_summary_table(result)}
        </section>

        <section class="ddg">
            <h2>Deployment Dependency Graph</h2>
            {self._generate_ddg_section(result)}
        </section>

        <section class="tier1">
            <h2>Tier 1: Deployment Metrics</h2>
            {self._generate_tier1_section(result)}
        </section>

        <section class="tier2">
            <h2>Tier 2: Integration Metrics</h2>
            {self._generate_tier2_section(result)}
        </section>

        <section class="tier3">
            <h2>Tier 3: Assumption Metrics</h2>
            {self._generate_tier3_section(result)}
        </section>

        {self._generate_tier4_section(result) if result.tier4 else ""}

        <footer>
            <p>Generated by <strong>aicoder-debt</strong></p>
        </footer>
    </div>
</body>
</html>"""
        return html

    def _get_styles(self) -> str:
        """Get CSS styles for the report.

        Returns:
            CSS string.
        """
        return """
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }
        header h1 {
            margin-bottom: 15px;
        }
        header code {
            background: rgba(255,255,255,0.2);
            padding: 2px 8px;
            border-radius: 4px;
        }
        section {
            background: white;
            padding: 25px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h2 {
            color: #667eea;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }
        h3 {
            color: #444;
            margin: 20px 0 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        th {
            background: #f8f9fa;
            font-weight: 600;
            color: #555;
        }
        tr:hover {
            background: #f8f9fa;
        }
        .metric-value {
            font-weight: 600;
            font-size: 1.1em;
        }
        .status-deployable { color: #28a745; }
        .status-repairable { color: #ffc107; }
        .status-irreparable { color: #dc3545; }
        .stat-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 15px 0;
        }
        .stat-card {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }
        .stat-card .value {
            font-size: 2em;
            font-weight: 700;
            color: #667eea;
        }
        .stat-card .label {
            color: #666;
            font-size: 0.9em;
        }
        .issue-list {
            max-height: 300px;
            overflow-y: auto;
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            font-family: monospace;
            font-size: 0.9em;
        }
        .issue-list li {
            margin: 5px 0;
            padding: 5px;
            border-bottom: 1px solid #eee;
        }
        code {
            background: #e9ecef;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 0.9em;
        }
        footer {
            text-align: center;
            padding: 20px;
            color: #666;
        }
        .progress-bar {
            background: #e9ecef;
            border-radius: 10px;
            height: 20px;
            overflow: hidden;
            margin: 10px 0;
        }
        .progress-bar .fill {
            height: 100%;
            background: linear-gradient(90deg, #667eea, #764ba2);
            transition: width 0.3s;
        }
        """

    def _generate_summary_table(self, result: "AnalysisResult") -> str:
        """Generate the summary metrics table.

        Args:
            result: Analysis result.

        Returns:
            HTML string.
        """
        dfr_class = f"status-{result.tier1.dfr.rating.value.lower()}"
        drd_value = result.tier1.drd.cost
        drd_display = str(drd_value) if drd_value >= 0 else "IRREPARABLE"

        rows = f"""
        <tr>
            <td>1</td>
            <td>DFR</td>
            <td class="metric-value {dfr_class}">{result.tier1.dfr.rating.value}</td>
            <td>Deployment Feasibility Rating</td>
        </tr>
        <tr>
            <td>1</td>
            <td>DRD</td>
            <td class="metric-value">{drd_display}</td>
            <td>Deployment Repair Distance</td>
        </tr>
        <tr>
            <td>1</td>
            <td>ID</td>
            <td class="metric-value">{result.tier1.id.stage.value} (gap: {result.tier1.id.gap})</td>
            <td>Illusion Depth ({result.tier1.id.stage_name})</td>
        </tr>
        <tr>
            <td>2</td>
            <td>ICR</td>
            <td class="metric-value">{result.tier2.icr.rate:.2f}</td>
            <td>Interface Consistency Rate</td>
        </tr>
        <tr>
            <td>2</td>
            <td>CCS</td>
            <td class="metric-value">{result.tier2.ccs.score:.2f}</td>
            <td>Configuration Coherence Score</td>
        </tr>
        <tr>
            <td>3</td>
            <td>URR</td>
            <td class="metric-value">{result.tier3.urr.rate:.2f}</td>
            <td>Undefined Reference Rate</td>
        </tr>
        <tr>
            <td>3</td>
            <td>HD</td>
            <td class="metric-value">{result.tier3.hd.density:.2f}</td>
            <td>Hallucination Density (per KLOC)</td>
        </tr>
        """

        if result.tier4:
            rows += f"""
        <tr>
            <td>4</td>
            <td>CSD</td>
            <td class="metric-value">{result.tier4.csd.density:.2f}</td>
            <td>Code Smell Density (per KLOC)</td>
        </tr>
        <tr>
            <td>4</td>
            <td>CCX</td>
            <td class="metric-value">{result.tier4.ccx.average:.2f}</td>
            <td>Cognitive Complexity Index</td>
        </tr>
            """

        return f"""
        <table>
            <thead>
                <tr>
                    <th>Tier</th>
                    <th>Metric</th>
                    <th>Value</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>
        """

    def _generate_ddg_section(self, result: "AnalysisResult") -> str:
        """Generate the DDG statistics section.

        Args:
            result: Analysis result.

        Returns:
            HTML string.
        """
        stats = result.ddg.statistics
        return f"""
        <div class="stat-grid">
            <div class="stat-card">
                <div class="value">{stats.total_nodes}</div>
                <div class="label">Nodes</div>
            </div>
            <div class="stat-card">
                <div class="value">{stats.total_edges}</div>
                <div class="label">Edges</div>
            </div>
            <div class="stat-card">
                <div class="value">{stats.total_cycles}</div>
                <div class="label">Cycles</div>
            </div>
            <div class="stat-card">
                <div class="value">{stats.irreparable_cycles}</div>
                <div class="label">Irreparable</div>
            </div>
        </div>
        <p><strong>Edge Types:</strong> ADDR: {stats.addr_edges}, STATE: {stats.state_edges}, RUNTIME: {stats.runtime_edges}</p>
        """

    def _generate_tier1_section(self, result: "AnalysisResult") -> str:
        """Generate Tier 1 details section.

        Args:
            result: Analysis result.

        Returns:
            HTML string.
        """
        dfr_class = f"status-{result.tier1.dfr.rating.value.lower()}"
        patterns_html = ""
        if result.tier1.drd.pattern_applications:
            patterns_list = "".join(
                f"<li>{p}</li>" for p in result.tier1.drd.pattern_applications
            )
            patterns_html = f"<h4>Repair Patterns:</h4><ul>{patterns_list}</ul>"

        return f"""
        <h3>DFR - Deployment Feasibility Rating</h3>
        <p><strong>Rating:</strong> <span class="{dfr_class}">{result.tier1.dfr.rating.value}</span></p>
        <p><strong>Reason:</strong> {result.tier1.dfr.reason}</p>

        <h3>DRD - Deployment Repair Distance</h3>
        <p><strong>Cost:</strong> {result.tier1.drd.cost if result.tier1.drd.cost >= 0 else "IRREPARABLE"}</p>
        {patterns_html}

        <h3>ID - Illusion Depth</h3>
        <p><strong>Highest Stage:</strong> {result.tier1.id.stage_name} (Stage {result.tier1.id.stage.value})</p>
        <p><strong>Gap from Deployment:</strong> {result.tier1.id.gap}</p>
        <div class="progress-bar">
            <div class="fill" style="width: {result.tier1.id.stage.value * 10}%"></div>
        </div>
        """

    def _generate_tier2_section(self, result: "AnalysisResult") -> str:
        """Generate Tier 2 details section.

        Args:
            result: Analysis result.

        Returns:
            HTML string.
        """
        unmatched_html = ""
        if result.tier2.icr.unmatched_calls:
            items = "".join(
                f"<li><code>{c.method} {c.endpoint}</code> at {c.file_path}:{c.line_number}</li>"
                for c in result.tier2.icr.unmatched_calls[:10]
            )
            if len(result.tier2.icr.unmatched_calls) > 10:
                items += f"<li>... and {len(result.tier2.icr.unmatched_calls) - 10} more</li>"
            unmatched_html = f"<h4>Unmatched Calls:</h4><ul class='issue-list'>{items}</ul>"

        unresolved_html = ""
        if result.tier2.ccs.unresolved_refs:
            items = "".join(
                f"<li><code>{r.key}</code> at {r.file_path}:{r.line_number}</li>"
                for r in result.tier2.ccs.unresolved_refs[:10]
            )
            if len(result.tier2.ccs.unresolved_refs) > 10:
                items += f"<li>... and {len(result.tier2.ccs.unresolved_refs) - 10} more</li>"
            unresolved_html = f"<h4>Unresolved Config References:</h4><ul class='issue-list'>{items}</ul>"

        return f"""
        <h3>ICR - Interface Consistency Rate</h3>
        <p><strong>Rate:</strong> {result.tier2.icr.rate:.2%}</p>
        <p><strong>Matched:</strong> {result.tier2.icr.matched_calls} / {result.tier2.icr.total_internal_calls}</p>
        {unmatched_html}

        <h3>CCS - Configuration Coherence Score</h3>
        <p><strong>Score:</strong> {result.tier2.ccs.score:.2%}</p>
        <p><strong>Resolved:</strong> {result.tier2.ccs.resolved_configs} / {result.tier2.ccs.total_config_refs}</p>
        {unresolved_html}
        """

    def _generate_tier3_section(self, result: "AnalysisResult") -> str:
        """Generate Tier 3 details section.

        Args:
            result: Analysis result.

        Returns:
            HTML string.
        """
        unresolved_html = ""
        if result.tier3.urr.unresolved_list:
            items = "".join(
                f"<li><code>{r.module}</code> at {r.file_path}:{r.line_number}</li>"
                for r in result.tier3.urr.unresolved_list[:10]
            )
            if len(result.tier3.urr.unresolved_list) > 10:
                items += f"<li>... and {len(result.tier3.urr.unresolved_list) - 10} more</li>"
            unresolved_html = f"<h4>Unresolved References:</h4><ul class='issue-list'>{items}</ul>"

        hallucinated_html = ""
        if result.tier3.hd.hallucinated_packages:
            items = "".join(
                f"<li><code>{p.package_name}</code> ({p.ecosystem}) at {p.file_path}:{p.line_number}</li>"
                for p in result.tier3.hd.hallucinated_packages[:10]
            )
            if len(result.tier3.hd.hallucinated_packages) > 10:
                items += f"<li>... and {len(result.tier3.hd.hallucinated_packages) - 10} more</li>"
            hallucinated_html = f"<h4>Hallucinated Packages:</h4><ul class='issue-list'>{items}</ul>"

        return f"""
        <h3>URR - Undefined Reference Rate</h3>
        <p><strong>Rate:</strong> {result.tier3.urr.rate:.2%}</p>
        <p><strong>Unresolved:</strong> {result.tier3.urr.unresolved_refs} / {result.tier3.urr.total_internal_refs}</p>
        {unresolved_html}

        <h3>HD - Hallucination Density</h3>
        <p><strong>Density:</strong> {result.tier3.hd.density:.2f} per KLOC</p>
        <p><strong>Hallucinated:</strong> {result.tier3.hd.hallucinated_count} / {result.tier3.hd.total_packages}</p>
        <p><strong>KLOC:</strong> {result.tier3.hd.kloc:.2f}</p>
        {hallucinated_html}
        """

    def _generate_tier4_section(self, result: "AnalysisResult") -> str:
        """Generate Tier 4 details section.

        Args:
            result: Analysis result.

        Returns:
            HTML string.
        """
        if not result.tier4:
            return ""

        severity_html = ""
        if result.tier4.csd.by_severity:
            items = "".join(
                f"<li>{sev}: {count}</li>"
                for sev, count in sorted(result.tier4.csd.by_severity.items())
            )
            severity_html = f"<h4>Issues by Severity:</h4><ul>{items}</ul>"

        complex_html = ""
        high_complexity = [f for f in result.tier4.ccx.functions if f.complexity > 10]
        if high_complexity:
            items = "".join(
                f"<li><code>{f.function_name}</code> (complexity: {f.complexity}) at {f.file_path}:{f.line_number}</li>"
                for f in sorted(high_complexity, key=lambda x: -x.complexity)[:10]
            )
            complex_html = f"<h4>High Complexity Functions:</h4><ul class='issue-list'>{items}</ul>"

        return f"""
        <section class="tier4">
            <h2>Tier 4: Maintainability Metrics</h2>

            <h3>CSD - Code Smell Density</h3>
            <p><strong>Density:</strong> {result.tier4.csd.density:.2f} per KLOC</p>
            <p><strong>Total Issues:</strong> {result.tier4.csd.total_issues}</p>
            <p><strong>KLOC:</strong> {result.tier4.csd.kloc:.2f}</p>
            {severity_html}

            <h3>CCX - Cognitive Complexity Index</h3>
            <p><strong>Average:</strong> {result.tier4.ccx.average:.2f}</p>
            <p><strong>Max Complexity:</strong> {result.tier4.ccx.max_complexity}</p>
            <p><strong>Total Functions:</strong> {result.tier4.ccx.total_functions}</p>
            <p><strong>High Complexity (>10):</strong> {result.tier4.ccx.high_complexity_count}</p>
            {complex_html}
        </section>
        """

    def save(self, result: "AnalysisResult", output_path: str | Path) -> None:
        """Save HTML report to file.

        Args:
            result: Analysis result to save.
            output_path: Path to output file.
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.generate(result), encoding="utf-8")
