// Contract Configuration
// Auto-generated by Multi-Agent DApp Generator


export const DeFi_Hybrid_TestConfig = {
  address: process.env.REACT_APP_DEFI_HYBRID_TEST_ADDRESS || "0x0000000000000000000000000000000000000000",
  abi: [
  {
    "inputs": [],
    "name": "getValue",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "newValue",
        "type": "uint256"
      }
    ],
    "name": "setValue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
]
};


// Combined contracts export
export const contracts = {
  DeFi_Hybrid_Test: DeFi_Hybrid_TestConfig,
}};

// Network configuration
export const networkConfig = {
  name: process.env.NETWORK || "localhost",
  rpcUrl: process.env.RPC_URL || "",
  chainId: parseInt(process.env.CHAIN_ID || "0")
};
