// Web3 Provider Context
// Auto-generated by Multi-Agent DApp Generator

import React, { createContext, useContext, useState, useEffect } from 'react';
import { ethers } from 'ethers';
import { contracts, networkConfig } from './contractConfig';

const Web3Context = createContext(null);

export const useWeb3 = () => {
  const context = useContext(Web3Context);
  if (!context) {
    throw new Error('useWeb3 must be used within Web3Provider');
  }
  return context;
};

export const Web3Provider = ({ children }) => {
  const [provider, setProvider] = useState(null);
  const [signer, setSigner] = useState(null);
  const [account, setAccount] = useState(null);
  const [contracts, setContracts] = useState({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    initializeWeb3();
  }, []);

  const initializeWeb3 = async () => {
    try {
      setLoading(true);
      setError(null);

      // Check if MetaMask is installed
      if (typeof window.ethereum === 'undefined') {
        throw new Error('MetaMask is not installed');
      }

      // Request account access
      await window.ethereum.request({ method: 'eth_requestAccounts' });

      // Create provider and signer
      const web3Provider = new ethers.BrowserProvider(window.ethereum);
      const web3Signer = await web3Provider.getSigner();
      const address = await web3Signer.getAddress();

      setProvider(web3Provider);
      setSigner(web3Signer);
      setAccount(address);

      // Initialize contract instances
      const contractInstances = {};
      contractInstances.defi_hybrid_test = new ethers.Contract(
        contracts.DeFi_Hybrid_Test.address,
        contracts.DeFi_Hybrid_Test.abi,
        web3Signer
      );

      setContracts(contractInstances);
      setLoading(false);
    } catch (err) {
      console.error('Web3 initialization error:', err);
      setError(err.message);
      setLoading(false);
    }
  };

  const connectWallet = async () => {
    await initializeWeb3();
  };

  const disconnectWallet = () => {
    setProvider(null);
    setSigner(null);
    setAccount(null);
    setContracts({});
  };

  const value = {
    provider,
    signer,
    account,
    contracts,
    loading,
    error,
    connectWallet,
    disconnectWallet,
    networkConfig
  };

  return <Web3Context.Provider value={value}>{children}</Web3Context.Provider>;
};
