// Backend Contract Integration
// Auto-generated by Multi-Agent DApp Generator

const { ethers } = require('ethers');

// Contract configuration
const CONTRACT_ADDRESS = process.env.DEFI_HYBRID_TEST_ADDRESS;
const CONTRACT_ABI = [
  {
    "inputs": [],
    "name": "getValue",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "newValue",
        "type": "uint256"
      }
    ],
    "name": "setValue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
];

// Network configuration
const RPC_URL = process.env.RPC_URL || 'http://localhost:8545';
const PRIVATE_KEY = process.env.PRIVATE_KEY; // Should be set in production

class ContractService {
  constructor() {
    this.provider = new ethers.JsonRpcProvider(RPC_URL);

    if (PRIVATE_KEY) {
      this.wallet = new ethers.Wallet(PRIVATE_KEY, this.provider);
      this.contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, this.wallet);
    } else {
      this.contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, this.provider);
    }
  }

  // Read contract state
  async getContractState() {
    try {
      // Example: Get basic contract info
      const address = await this.contract.getAddress();
      return { address };
    } catch (error) {
      console.error('Error reading contract state:', error);
      throw error;
    }
  }

  // Listen to contract events
  listenToEvents(eventName, callback) {
    this.contract.on(eventName, callback);
  }

  // Stop listening to events
  removeListener(eventName, callback) {
    this.contract.off(eventName, callback);
  }
}

module.exports = { ContractService };
